### ISSUE TITLE
[F2V] Lock indicator

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/files_lock#154]
In preparation for Nextcloud 28 where larger parts of the files app are migrated to vue we need to adjust our integration with the file list for the lock indicator:

## Screenshots of the current state

![Screenshot 2023-07-19 at 08 44 52](https://github.com/nextcloud/files_lock/assets/3404133/75f98f50-b4ee-4834-9a17-04b259e1803f)
![Screenshot 2023-07-19 at 08 45 02](https://github.com/nextcloud/files_lock/assets/3404133/ca64fc08-6993-4b3c-a4e6-3a3b2c207378)
![Screenshot 2023-07-19 at 08 45 05](https://github.com/nextcloud/files_lock/assets/3404133/e1e658f4-e2a1-406c-8262-9c931f3bcd3a)

## Current code

- Fetch lock status with additional properties during files app propfind, rather hacky but the pattern is also used in other apps
- Register 3 file actions
	- Inline for the lockindicator which is manually added on top of the three dots menu
	- Lock/unlock action button in the actions menu
	- Lock details action just for informational purposes to tell who locked the file

https://github.com/nextcloud/files_lock/blob/main/js/files.js

I'd like to on the one hand raise this for design discussion from @nextcloud/designers as this may be a chance to adapt the design with the vue rewrite.

On the other hand the current approach likely won't work with the fresh fileactions API, so it would be great to get some insight from @skjnldsv for how we could achieve showing the lock status. I'm actually considering if we shouldn't rather move showing the lock status to the files app itself, as the mid-term plan discussed with @AndyScherzinger was anyways to have the files_lock app become integrated into server. If we want to keep the code separated we may need to think about hooking points to add the inline indicator

**Comment by juliushaertl** [comment]
Another note, we should probably reconsider the positioning above the three-dots menu as this will be quite tough to get back in vue without dirty hacks I could imagine.

**Comment by marcoambrosini** [comment]
@juliushaertl As far as the lock indicator goes, I would decouple it from the actions menu and move it to the file icon, which is where most likely the user's eyes will scan first, together with with the title. 
On the right we can have our normal action menu with all the action related to file locking.

**Comment by juliushaertl** [comment]
Any suggestions where to put it exactly? The main concern regarding putting it to the preview is that we already might have the favorite indicator on that and two icons might be too much for badges on the small previews.

**Comment by marcoambrosini** [comment]
It's also true, I just tested in mockups and it doesn't look good. To be honest the favourite icon doesn't look good either. 

I just find this icon combination confusing, especially because the menu contain actions that are not related at all to locking the file, so people that might be looking for those actions might have it hard to find them

**Comment by szaimen** [comment]
What about doing it like this?
![image](https://github.com/nextcloud/files_lock/assets/42591237/cd301776-ff7f-44b8-8fd8-df02ff46fa5e)
or maybe like this?
![image](https://github.com/nextcloud/files_lock/assets/42591237/4a0b067f-e427-4d9b-81b0-e3c4c1f1c1ab)

**Comment by marcoambrosini** [comment]
I tried those too yesterday @szaimen but I wasn't convinced. 
To be honest I would just show everything inline as there is plenty of space for it on a laptop. 

On mobile views and apps, I would use 2 liner component and their sub-line to track the state of favourite and locked (On mobile apps we already use 2 liners)  

e.g.
<img width="649" alt="Screenshot 2023-07-20 at 14 50 40" src="https://github.com/nextcloud/files_lock/assets/26852655/fff6a926-dd63-4293-8f33-5e97c428d9d5">

**Comment by szaimen** [comment]
> e.g.
> <img alt="Screenshot 2023-07-20 at 14 50 40" width="649" src="https://user-images.githubusercontent.com/26852655/254783555-fff6a926-dd63-4293-8f33-5e97c428d9d5.png">

Indeed this looks very good but I guess it would be a new pattern for the web?

**Comment by nimishavijay** [comment]
Love the mobile view! For web my worry with showing it at the beginning is either removing the filetype icon which is useful for scanning, or disturbing the alignment of the text (if one of the files has the lock in front of it, the starting point of the text will be shifted to the right). 

How about showing it at the end of the file name? (still I'm not fully convinced because when someone clicks on "Lock file" from the action menu the indication that the file was locked is quite far off from where you clicked, but just throwing another idea in the mix). 

![image](https://github.com/nextcloud/files_lock/assets/52440189/43d0c587-2f3c-40b5-a515-25e871c8297a)

**Comment by AndyScherzinger** [comment]
Mobile view looks nice and is neat in case we talk native apps, for web I suspect this causes a a11y issue since you break the concept of a table-structure and this will fail the BITV check, but just to be sure adding @JuliaKirschenheuter

**Comment by marcoambrosini** [comment]
> How about showing it at the end of the file name?

Yes @nimishavijay  :)  
Even on that rather narrow window you've just screnshotted, there's plenty of space to show the lock and favourite icons inline.

> break the concept of a table-structure and this will fail the BITV check

@AndyScherzinger I think it can still be a table. We can have a `div` with two paragraphs in it within the table data cell element. My mockup is a bit misleading because it looks like a talk conversation, but it could be a table's row. And the wider it is, the more column with information can pop up making it eventually into a 1 line row.

**Comment by AndyScherzinger** [comment]
I don't think that is accessible, but I am happy to be proven otherwise 👍 @JuliaKirschenheuter @michaelnissenbaum is https://github.com/nextcloud/files_lock/issues/154#issuecomment-1643283214 considered accessible also with https://github.com/nextcloud/files_lock/issues/154#issuecomment-1644941730 (second paragraph) in mind?

**Comment by skjnldsv** [comment]
@marcoambrosini dublines are not accessible in that matter.
Let's avoid this please.

Having the lock icon inline as suggest is the way to go.
Let's keep things simple and compliant with the API.
Julius's proposal with the three actions is good. Have the lock indicator and the locked info/unlock actions in the actions menu.

![image](https://github.com/nextcloud/files_lock/assets/14975046/7ac2d96f-ae26-4991-bb7c-5fed6626a279)

**Comment by skjnldsv** [comment]
PS: clicking the icon could just open the actions menu showing the locking informations and the unlock action.
The flow will be accessible and simple enough :)

**Comment by marcoambrosini** [comment]
My only concern was the double-icon button, which I thought existed to save those 44px of horizontal space. The 2-liner component on narrow screens was an attempt to address that. 
But if we have enough width for it, by all means let's do always inline!
