### ISSUE TITLE
Honor LOCK and UNLOCK from WebDAV requests

### ISSUE THREAD

**Issue by solracsf** [nextcloud/files_lock#44]
Would be a great option if `LOCK` and `UNLOCK` methods from WebDAV would be honored by the app so WebDAV could be more "user friendly" for files opened and closed, as WebDAV clients send those methods but they are not understood/honored by the `server`.

To be clear:
- LOCK request = issue a LOCK on file
- UNLOCK request = issue a UNLOCK on file

**Comment by juliushaertl** [comment]
I had a look into implementing LOCK/UNLOCK support through webdav, however it seems that the current approach of locking per user and basically allowing the user owning the lock is conflicting with the approach that webdav uses where a lock is identified by a token which then needs to be sent with the actual file operation through the `If` header which is currently not done by the web UI.

- We should probably implement https://github.com/sabre-io/dav/blob/75e3e888a469eb39773ff1389c2666b48df73dca/lib/DAV/Locks/Backend/BackendInterface.php instead of a custom plugin
  - However that way writing to locked files is then bound to the token instead of the current user
  - We could make the lock differ between a webdav lock (per client) and a user triggered lock (per user), but then we would not stick to the webdav standard fully
  - Storing the lock token when creating the lock would be cleaner but also a larger implementation effort on the client side including the web UI
- The implementation should pass the litmus locking tests

**Comment by juliushaertl** [comment]
First steps to prepare for this made in #54 the missing parts would be to implement the BackendInterface methods to properly handle WebDAV lock especially with their differentiation of shared/exclusive locking and proper handling of the token matching within the storage wrapper abstraction. The token is matched already in the If header by Sabre.

**Comment by solracsf** [comment]
@juliushaertl may I ask if this will also handle calls from the desktop clients as well (as they speak WebDAV)?
If yes, this could be a very recommended app to install alongside client deployments.
