### ISSUE TITLE
File locking currently only 30min

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/files_lock#49]
As dicussced in https://github.com/nextcloud/server/issues/21914 I assumed that file locking will be "forever", but Maxence said that current state locks file only for 30min, which could be changed to a config value.
This means that longer editing of a file is not possible.
On the other hand it means that we do not need to have any unlock mechanism via admin.

@AndyScherzinger @schiessle what is your opinion here?

**Comment by AndyScherzinger** [comment]
Well I'd be fine either way.

- lock ```forever``` but rather hard-coded or the config value would have have a quite high lower-boundry because, see option 2
- lock-time via config: clients now not just need to handle lock/unlock but also deal with a "lock-steal" situation, where lock time is e.g. 4h and a user works on the doc for 6h, tries to save, but no another used grabbed the lock after the file auto-unlocked. Also then the discussion will start that the client should "update the lock-timeframe" whenever a save is triggers or other ideas.

So my take is 
- change it to "forever" as the default
- state in the config that other values are possible but handling isn't supported by clients
- implement admin unlock since you face the same situation with a lock set to 3+ weeks for example
